version: 'version 3'
services:
  nginx:
    build: .
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    environment:
      - NGINX_SERVER_NAME=localhost
      - NGINX_SSL_CERT=/etc/nginx/ssl/localhost.crt
      - NGINX_SSL_KEY=/etc/nginx/ssl/localhost.key
      - VITE_BACKEND_API_URL="localhost:12000/api"
      - VITE_BACKEND_WS_URL="localhost:12000/ws"
      - VITE_BACKEND_SECURE=false
  backend:
    build: ./quackamole-rtc-server
    ports:
      - 12000:12000
