version: 'version 3'
services:
  nginx:
    build:
      context: .
      args:
        - VITE_BACKEND_API_URL=localhost/api
        - VITE_BACKEND_WS_URL=localhost/ws
        - VITE_BACKEND_SECURE=true
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./quackamole-rtc-server/test:/etc/nginx/ssl
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf # to retain syntax highlighting
      - NGINX_SERVER_NAME=localhost
      - NGINX_SSL_CERT=/etc/nginx/ssl/localhost.crt
      - NGINX_SSL_KEY=/etc/nginx/ssl/localhost.key
  backend:
    build: ./quackamole-rtc-server
    # ports:
    #   - 12000:12000 # <--------- by not exposing port we can only access it via nginx proxy. Uncomment for direct access
